### ISSUE TITLE
make install only places files in /usr/lib

### ISSUE THREAD

**Issue by aclater** [colinbourassa/libcomm14cux#10]
On Fedora 33, the default library search path is /usr/lib64 symlinks should be placed accordingly

lrwxrwxrwx. 1 root root 28 Nov 23 12:15 /usr/lib64/libcomm14cux.so -> ../lib/libcomm14cux.so.2.1.1
lrwxrwxrwx. 1 root root 28 Nov 23 12:15 /usr/lib64/libcomm14cux.so.2 -> ../lib/libcomm14cux.so.2.1.1
lrwxrwxrwx. 1 root root 28 Nov 23 12:15 /usr/lib64/libcomm14cux.so.2.1.1 -> ../lib/libcomm14cux.so.2.1.1

**Comment by colinbourassa** [comment]
Thanks for the report. It's been a while since I've touched this, and I've recently learned of [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html), which should be the simplest way of resolving it. I'll commit a fix soon.

**Comment by colinbourassa** [comment]
The 2.1.2 release uses GNUInstallDirs, so it should pick up the appropriate paths for your system (as long as they're known by CMake.)
