### ISSUE TITLE
[HARDWARE] Getting a Audrino programming cable working.

### ISSUE THREAD

**Issue by bardiharborow** [colinbourassa/libcomm14cux#9]
Hi,

Just a hardware question here. I bought a Arduino programming cable to test. I ran the PuTTY test and it worked as expected. Then I inverted the Rx line as described. The PuTTY test however still works. I'm going to test it in a few days (waiting on the resistor), but I think I may have done something wrong. Could I get someone to compare the below with a working cable?

FT_Prog template export:
```xml
<?xml version="1.0" encoding="utf-16"?>
<FT_EEPROM>
  <Chip_Details>
    <Type>FT232R</Type>
  </Chip_Details>
  <USB_Device_Descriptor>
    <VID_PID>0</VID_PID>
    <idVendor>0403</idVendor>
    <idProduct>6001</idProduct>
    <bcdUSB>USB 2.0</bcdUSB>
  </USB_Device_Descriptor>
  <USB_Config_Descriptor>
    <bmAttributes>
      <RemoteWakeupEnabled>true</RemoteWakeupEnabled>
      <SelfPowered>false</SelfPowered>
      <BusPowered>true</BusPowered>
    </bmAttributes>
    <IOpullDown>false</IOpullDown>
    <MaxPower>90</MaxPower>
  </USB_Config_Descriptor>
  <USB_String_Descriptors>
    <Manufacturer>FTDI</Manufacturer>
    <Product_Description>FT232R USB UART</Product_Description>
    <SerialNumber_Enabled>true</SerialNumber_Enabled>
    <SerialNumber />
    <SerialNumberPrefix>A4</SerialNumberPrefix>
    <SerialNumber_AutoGenerate>true</SerialNumber_AutoGenerate>
  </USB_String_Descriptors>
  <Hardware_Specific>
    <HighIO>false</HighIO>
    <D2XX>false</D2XX>
    <ExternalOscillator>false</ExternalOscillator>
    <Invert_RS232_Signals>
      <TXD>false</TXD>
      <RXD>true</RXD>
      <RTS>false</RTS>
      <CTS>false</CTS>
      <DTR>false</DTR>
      <DSR>false</DSR>
      <DCD>false</DCD>
      <RI>false</RI>
    </Invert_RS232_Signals>
    <IO_Controls>
      <C0>TXLED#</C0>
      <C1>RXLED#</C1>
      <C2>TXDEN</C2>
      <C3>PWREN#</C3>
      <C4>SLEEP#</C4>
    </IO_Controls>
  </Hardware_Specific>
</FT_EEPROM>
```

P.S. I might as well ask a few questions as well. I am a developer, so let me know if the code needs something doing. I am also thinking of producing cords and selling them on eBay (if I can get this one working. of course). Do you know if there is any demand?

**Comment by colinbourassa** [comment]
After you inverted the RXD line with FT Prog, did you write the new EEPROM image to the device? A lot of people miss this step; you need to select "Program" from the "Devices" menu to actually make the change to the FTDI hardware.

There is probably still a good amount of demand for cables. I know of a few people on both sides of the Atlantic that are building and selling them, and over the past couple years they have moved close to 1,000 units in total.

**Comment by bardiharborow** [comment]
I was reviewing my old GitHub issues and came across this. If I recall, the issue was just as you described. Nice software by the way.
